### PR TITLE
[TASK] Provide eventId in reconsituted feed event

### PR DESCRIPTION
**Pull request by ohader**

### CODE REVIEW

**Comment by dbellettini** [comment]
This change is trivial but I think this must be tested nonetheless, either by adding an assertion to an existing test case or writing a new one

**Comment by ohader** [comment]
-1 something's wrong with my new test on node-cluster

**Comment by ohader** [comment]
Alright, I had to search a bit in the ES history... The reason for the test failures in the ES 3.0.5 scenario is the missing support of the event-id in the JSON response. By reading the [3.1.0 ChangeLog](https://github.com/EventStore/EventStore/releases/tag/oss-v3.1.0) it seems, that Greg introduced event-id in that version the first time [6a1655c], see (https://github.com/EventStore/EventStore/commit/6a1655c).

**Comment by ohader** [comment]
Davide, do you need more tests or information on this one? If so, just let me know please...

**Comment by dbellettini** [comment]
I'm sorry I was on vacation, tomorrow I will check it out

**Pull request merged**
